### PR TITLE
Clean the code up, add tests

### PR DESCRIPTION
**Pull request by sallar**
This PR does the following:

+ Adds tests
+ Cleans up formatting
+ Convert `export default` to `module.exports` because users of this module might not be transpiling their node_modules folder so this needs to be standards compliant.
+ Adds Travis config file (for running tests automatically)
+ Adds LICENSE

### CODE REVIEW

**Comment by sallar** [comment]
Thanks @sajjad-shirazy can you publish to npm too?

**Comment by ziaenezhad** [comment]
Thanks @sallar, i'm really glad you are here, i know you and your works from at least 5 years ago :)

> Thanks @sajjad-shirazy can you publish to npm too?

sure

**Comment by sallar** [comment]
@sajjad-shirazy cheers man. my please :) Keep up the great work 👍

**Comment by ziaenezhad** [comment]
the node package is up.
Thanks again

**Comment by sallar** [comment]
@sajjad-shirazy using the package to fix a few issues here: https://github.com/wulkano/kap/pull/346/files :) cheers

**Comment by ziaenezhad** [comment]
@sallar, Very nice to hear it was useful :)

**Pull request merged**
